### ISSUE TITLE
As a user, I want a user panel to view my information.

### ISSUE THREAD

**Issue by FYK96** [samgo1/Soen341#77]
User panel includes all issued involving user information such as profile page and user panel.

- [x] Fixed on a screen #49 
- [ ] Should contain "My "Questions" & "My Answers" #28 
- [x] Should check if user is signed in #78
